# Generated by Django 4.1.2 on 2022-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homework", models.TextField()),
                ("homeworkDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentName", models.CharField(max_length=20)),
                ("studentGrade", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="StudyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studyProgress", models.TextField()),
                ("studyDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Wage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wageWay", models.CharField(max_length=10)),
                ("wagePrice", models.IntegerField()),
            ],
        ),
    ]
